[phases.setup]
aptPkgs = [
  'chromium',
  'chromium-browser',
  'google-chrome-stable',
  'snapd',
  'wget',
  'gnupg',
  'ca-certificates',
  'fonts-liberation',
  'fonts-roboto',
  'fonts-noto-color-emoji',
  'libappindicator3-1',
  'libasound2t64',
  'libatk-bridge2.0-0',
  'libatk1.0-0',
  'libatspi2.0-0',
  'libdrm2',
  'libgtk-3-0',
  'libgtk-4-1',
  'libnspr4',
  'libnss3',
  'libx11-6',
  'libxcomposite1',
  'libxcursor1',
  'libxdamage1',
  'libxext6',
  'libxfixes3',
  'libxi6',
  'libxrandr2',
  'libxrender1',
  'libxss1',
  'libxtst6',
  'libgbm1',
  'libglib2.0-0',
  'libgconf-2-4',
  'libxss1',
  'libgconf-2-4',
  'xdg-utils',
  'xvfb'
]
cmds = [
  'echo "=== Enhanced Chromium Installation Setup ==="',
  'echo "Updating package lists..."',
  'apt-get update -y',
  'echo "=== Installing Primary Chromium Packages ==="',
  'apt-get install -y --no-install-recommends chromium chromium-browser || echo "Primary chromium installation failed, continuing..."',
  'echo "=== Installing Google Chrome as Fallback ==="',
  'wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - 2>/dev/null || echo "Google signing key installation failed"',
  'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list 2>/dev/null || echo "Chrome repository setup failed"',
  'apt-get update -y 2>/dev/null || echo "Chrome repository update failed"',
  'apt-get install -y --no-install-recommends google-chrome-stable 2>/dev/null || echo "Google Chrome installation failed"',
  'echo "=== Installing Snap Chromium as Final Fallback ==="',
  'snap install chromium 2>/dev/null || echo "Snap chromium installation failed"',
  'echo "=== Comprehensive Chromium Detection ==="',
  'echo "Searching for Chromium executables in multiple locations..."',
  'echo "--- /usr/bin search ---"',
  'find /usr/bin -name "*chromium*" -type f 2>/dev/null | head -10 || echo "No chromium in /usr/bin"',
  'find /usr/bin -name "*chrome*" -type f 2>/dev/null | head -10 || echo "No chrome in /usr/bin"',
  'echo "--- /usr/local/bin search ---"',
  'find /usr/local/bin -name "*chromium*" -o -name "*chrome*" 2>/dev/null | head -5 || echo "No chromium/chrome in /usr/local/bin"',
  'echo "--- /opt search ---"',
  'find /opt -name "*chromium*" -o -name "*chrome*" 2>/dev/null | head -5 || echo "No chromium/chrome in /opt"',
  'echo "--- /snap/bin search ---"',
  'find /snap/bin -name "*chromium*" -o -name "*chrome*" 2>/dev/null | head -5 || echo "No chromium/chrome in /snap/bin"',
  'echo "=== Enhanced Chromium Path Detection ==="',
  'CHROMIUM_PATHS=$(find /usr/bin /usr/local/bin /opt /snap/bin -name "*chromium*" -o -name "*chrome*" 2>/dev/null | grep -E "(chromium|chrome)" | head -20)',
  'echo "Found potential Chromium paths:"',
  'echo "$CHROMIUM_PATHS" || echo "No Chromium paths found"',
  'echo "=== Selecting Best Chromium Executable ==="',
  'BEST_CHROMIUM=""',
  'for path in /usr/bin/chromium /usr/bin/chromium-browser /usr/bin/google-chrome-stable /usr/bin/google-chrome /snap/bin/chromium /opt/google/chrome/chrome; do',
  '  if [ -f "$path" ] && [ -x "$path" ]; then',
  '    echo "✅ Found executable: $path"',
  '    BEST_CHROMIUM="$path"',
  '    break',
  '  else',
  '    echo "❌ Not found or not executable: $path"',
  '  fi',
  'done',
  'echo "Selected Chromium executable: $BEST_CHROMIUM"',
  'echo "=== Creating Robust Symlinks ==="',
  'if [ -n "$BEST_CHROMIUM" ] && [ -f "$BEST_CHROMIUM" ]; then',
  '  echo "Creating symlinks from $BEST_CHROMIUM..."',
  '  ln -sf "$BEST_CHROMIUM" /usr/bin/chromium 2>/dev/null && echo "✅ /usr/bin/chromium symlink created" || echo "❌ Failed to create /usr/bin/chromium symlink"',
  '  ln -sf "$BEST_CHROMIUM" /usr/bin/chromium-browser 2>/dev/null && echo "✅ /usr/bin/chromium-browser symlink created" || echo "❌ Failed to create /usr/bin/chromium-browser symlink"',
  '  ln -sf "$BEST_CHROMIUM" /usr/bin/google-chrome 2>/dev/null && echo "✅ /usr/bin/google-chrome symlink created" || echo "❌ Failed to create /usr/bin/google-chrome symlink"',
  '  ln -sf "$BEST_CHROMIUM" /usr/bin/google-chrome-stable 2>/dev/null && echo "✅ /usr/bin/google-chrome-stable symlink created" || echo "❌ Failed to create /usr/bin/google-chrome-stable symlink"',
  '  chmod +x "$BEST_CHROMIUM" 2>/dev/null || echo "chmod failed for $BEST_CHROMIUM"',
  '  echo "Symlinks created successfully using: $BEST_CHROMIUM"',
  'else',
  '  echo "⚠️  WARNING: No working Chromium executable found for symlink creation"',
  '  echo "Creating fallback symlinks anyway..."',
  '  touch /usr/bin/chromium && chmod +x /usr/bin/chromium || echo "Failed to create fallback chromium"',
  'fi',
  'echo "=== Final Verification ==="',
  'echo "Listing all chromium-related files in /usr/bin:"',
  'ls -la /usr/bin/*chromium* /usr/bin/*chrome* 2>/dev/null || echo "No chromium/chrome files in /usr/bin"',
  'echo "=== Testing Final Installation ==="',
  'for testpath in /usr/bin/chromium /usr/bin/chromium-browser /usr/bin/google-chrome /usr/bin/google-chrome-stable; do',
  '  if [ -x "$testpath" ]; then',
  '    echo "Testing $testpath..."',
  '    $testpath --version 2>&1 | head -1 || echo "Version check failed for $testpath"',
  '    timeout 10s $testpath --no-sandbox --disable-dev-shm-usage --disable-gpu --headless --virtual-time-budget=1000 about:blank 2>&1 >/dev/null && echo "✅ $testpath startup test passed" || echo "❌ $testpath startup test failed"',
  '  else',
  '    echo "❌ $testpath not executable"',
  '  fi',
  'done',
  'echo "=== Enhanced Chromium Setup Complete ==="'
]

[phases.install]
dependsOn = ['setup']
cmds = ['npm install']

[phases.build]
dependsOn = ['install'] 
cmds = [
  'npm run build',
  'echo "Build verification - checking Chromium availability:"',
  'node -e "console.log(\"Chromium paths check:\"); const fs = require(\"fs\"); const paths = [\"/usr/bin/chromium-browser\", \"/usr/bin/chromium\", \"/usr/bin/google-chrome\"]; paths.forEach(p => console.log(p + \":\", fs.existsSync(p) ? \"EXISTS\" : \"MISSING\"));"'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium'
SUPABASE_URL = 'https://jbwbiomnsbpmcnjgzrqp.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impid2Jpb21uc2JwbWNuamd6cnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDMwNjUsImV4cCI6MjA2ODgxOTA2NX0.oq60ZEcsO6u1CqVJDqQJ58CiUnFkxMUY8Mn9dTUFQ9I'

[build]
env = ['NODE_ENV=production', 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true', 'PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium']
