[phases.setup]
aptPkgs = [
  'chromium-browser',
  'fonts-liberation',
  'fonts-roboto',
  'fonts-noto-color-emoji',
  'fonts-dejavu-core',
  'fontconfig',
  'fonts-ipafont-gothic',
  'fonts-wqy-zenhei',
  'fonts-thai-tlwg',
  'fonts-kacst',
  'fonts-freefont-ttf',
  'libappindicator3-1',
  'libasound2t64',
  'libatk-bridge2.0-0',
  'libatk1.0-0',
  'libatspi2.0-0',
  'libdrm2',
  'libgtk-3-0',
  'libgtk-4-1',
  'libnspr4',
  'libnss3',
  'libx11-6',
  'libxcomposite1',
  'libxcursor1',
  'libxdamage1',
  'libxext6',
  'libxfixes3',
  'libxi6',
  'libxrandr2',
  'libxrender1',
  'libxss1',
  'libxtst6',
  'libgbm1',
  'libglib2.0-0',
  'libxshmfence1',
  'libglu1-mesa',
  'xdg-utils',
  'xvfb',
  'wget',
  'ca-certificates'
]
cmds = [
  'echo "=== Docker-Compatible Chromium Installation ==="',
  'apt-get update -y',
  'echo "Installing Chromium via APT (Docker-compatible)..."',
  'apt-get install -y chromium-browser',
  'echo "Creating standard symlinks..."',
  'ln -sf /usr/bin/chromium-browser /usr/bin/chromium',
  'ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome',
  'chmod +x /usr/bin/chromium',
  'chmod +x /usr/bin/chromium-browser',
  'echo "Verifying installation..."',
  'which chromium-browser',
  'chromium-browser --version',
  'echo "Testing headless mode..."',
  'timeout 10s chromium-browser --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --virtual-time-budget=2000 about:blank || echo "Headless test completed"',
  'echo "=== Chromium Installation Complete ==="'
]

[phases.install]
dependsOn = ['setup']
cmds = ['npm install']

[phases.build]
dependsOn = ['install'] 
cmds = [
  'npm run build',
  'echo "Build verification - checking Chromium availability:"',
  'node -e "console.log(\"Chromium paths check:\"); const fs = require(\"fs\"); const paths = [\"/usr/bin/chromium-browser\", \"/usr/bin/chromium\", \"/usr/bin/google-chrome\"]; paths.forEach(p => console.log(p + \":\", fs.existsSync(p) ? \"EXISTS\" : \"MISSING\"));"'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium-browser'
SUPABASE_URL = 'https://jbwbiomnsbpmcnjgzrqp.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impid2Jpb21uc2JwbWNuamd6cnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDMwNjUsImV4cCI6MjA2ODgxOTA2NX0.oq60ZEcsO6u1CqVJDqQJ58CiUnFkxMUY8Mn9dTUFQ9I'

[build]
env = ['NODE_ENV=production', 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true', 'PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser']
