[phases.setup]
aptPkgs = ['chromium', 'chromium-sandbox']

[phases.build]
dependsOn = ['setup']

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium'

[build]
env = ['PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true', 'PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium']
